[package]
name = "v_1"
version = "0.1.0"
authors = ["shenshing <lyshenshing20@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.6"  
crypto-hash = "0.3.3"
rust-crypto = "0.2.36"
rustc-serialize = "0.3.24"
base64-stream = "1.0.3"
rand = "0.6"
rand_core = "0.4.0"